"""Faithful, provenance-aware ThermoML ingestion and tabular export."""

from .analysis import (
    CollectionSummary,
    RankedCount,
    summarize_collection,
    summarize_documents,
)
from .archive import (
    ArchiveAnalysis,
    ArchiveCatalog,
    ArchiveComponentIndex,
    ArchiveParseFailure,
    ArchiveQueryResult,
    ArchiveRecovery,
    CatalogEntry,
    PublicationRank,
    RankedDataset,
    analyze_thermoml_archive,
    catalog_thermoml_archive,
    index_thermoml_archive,
    iter_thermoml_archive,
    query_thermoml_archive,
)
from .bibliography import PublicationCitation, publication_citation
from .classification import classify_property
from .collection import DatasetMatch, ThermoMLCollection
from .conformance import (
    ConformanceSource,
    get_conformance_source,
    list_conformance_sources,
)
from .errors import (
    AmbiguousComponentError,
    ComponentNotFoundError,
    ComponentResolutionError,
    OptionalDependencyError,
    PubChemResolutionError,
    ThermoMLArchiveError,
    ThermoMLDownloadError,
    ThermoMLError,
    ThermoMLParseError,
    ThermoMLReferenceError,
    ThermoMLSourceError,
    ThermoMLValidationError,
)
from .identity import ComponentIdentity, ComponentIndex, ComponentQuery
from .models import (
    Citation,
    Compound,
    ConstraintDefinition,
    DataPoint,
    DataSet,
    DeviceSpecification,
    MeasuredValue,
    PropertyDefinition,
    PurityAssessment,
    Repeatability,
    Sample,
    SourceProvenance,
    SourceRecovery,
    ThermoMLDocument,
    Uncertainty,
    VariableDefinition,
)
from .parser import (
    load_thermoml_json_url,
    load_thermoml_url,
    parse_thermoml,
    parse_thermoml_json,
    validate_xml_schema,
)
from .pubchem import PubChemNamespace, resolve_pubchem_component
from .table import (
    ExperimentalTable,
    build_analysis_table,
    build_experimental_table,
    build_property_table,
)
from .upstream import (
    ArchiveSource,
    CordraSnapshot,
    archive_source_record,
    cordra_snapshot_record,
    default_cache_dir,
    discover_archive_source,
    discover_cordra_snapshot,
    fetch_thermoml_archive,
    get_archive_source,
    get_cordra_snapshot,
)

__version__ = "0.1.3"

__all__ = [
    "AmbiguousComponentError",
    "ArchiveAnalysis",
    "ArchiveCatalog",
    "ArchiveComponentIndex",
    "ArchiveParseFailure",
    "ArchiveQueryResult",
    "ArchiveRecovery",
    "ArchiveSource",
    "CatalogEntry",
    "Citation",
    "CollectionSummary",
    "ComponentIdentity",
    "ComponentIndex",
    "ComponentNotFoundError",
    "ComponentQuery",
    "ComponentResolutionError",
    "Compound",
    "ConformanceSource",
    "ConstraintDefinition",
    "CordraSnapshot",
    "DataPoint",
    "DataSet",
    "DatasetMatch",
    "DeviceSpecification",
    "ExperimentalTable",
    "MeasuredValue",
    "OptionalDependencyError",
    "PropertyDefinition",
    "PubChemNamespace",
    "PubChemResolutionError",
    "PublicationCitation",
    "PublicationRank",
    "PurityAssessment",
    "RankedCount",
    "RankedDataset",
    "Repeatability",
    "Sample",
    "SourceProvenance",
    "SourceRecovery",
    "ThermoMLArchiveError",
    "ThermoMLCollection",
    "ThermoMLDocument",
    "ThermoMLDownloadError",
    "ThermoMLError",
    "ThermoMLParseError",
    "ThermoMLReferenceError",
    "ThermoMLSourceError",
    "ThermoMLValidationError",
    "Uncertainty",
    "VariableDefinition",
    "analyze_thermoml_archive",
    "archive_source_record",
    "build_analysis_table",
    "build_experimental_table",
    "build_property_table",
    "catalog_thermoml_archive",
    "classify_property",
    "cordra_snapshot_record",
    "default_cache_dir",
    "discover_archive_source",
    "discover_cordra_snapshot",
    "fetch_thermoml_archive",
    "get_archive_source",
    "get_conformance_source",
    "get_cordra_snapshot",
    "index_thermoml_archive",
    "iter_thermoml_archive",
    "list_conformance_sources",
    "load_thermoml_json_url",
    "load_thermoml_url",
    "parse_thermoml",
    "parse_thermoml_json",
    "publication_citation",
    "query_thermoml_archive",
    "resolve_pubchem_component",
    "summarize_collection",
    "summarize_documents",
    "validate_xml_schema",
]
